/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * a model for a long list of batches with potential future paging support
 *
 */
class AllBatchesPageResponse {
  /**
   * Create a AllBatchesPageResponse.
   * @member {number} [pageIndex] the current page (0 based)
   * @member {number} [totalPages] the total number of pages
   * @member {array} [batches] a list of batches with urls for individual batch
   * reports
   */
  constructor() {
  }

  /**
   * Defines the metadata of AllBatchesPageResponse
   *
   * @returns {object} metadata of AllBatchesPageResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AllBatchesPageResponse',
      type: {
        name: 'Composite',
        className: 'AllBatchesPageResponse',
        modelProperties: {
          pageIndex: {
            required: false,
            serializedName: 'pageIndex',
            type: {
              name: 'Number'
            }
          },
          totalPages: {
            required: false,
            serializedName: 'totalPages',
            type: {
              name: 'Number'
            }
          },
          batches: {
            required: false,
            serializedName: 'batches',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'BatchLinkResponseElementType',
                  type: {
                    name: 'Composite',
                    className: 'BatchLinkResponse'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = AllBatchesPageResponse;
