/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * A summary of batch compute time and pending, failed and completed operations
 *
 */
class BatchReportResponse {
  /**
   * Create a BatchReportResponse.
   * @member {number} [aggregateComputeTime] the total amount of CPU time spent
   * on this batch. if there are pending operations,
   * then this figure is not final
   * @member {string} [status] True if all operations in batch have been
   * processed. Possible values include: 'pending', 'finished'
   * @member {date} [created] when the batch was submitted
   * @member {array} [pending] list of id/summary endpoint for operations that
   * are still pending
   * @member {array} [completed] list of id/summary endpoint for operations
   * that are completed
   * @member {array} [failed] list of id/summary endpoint for operations that
   * have failed
   */
  constructor() {
  }

  /**
   * Defines the metadata of BatchReportResponse
   *
   * @returns {object} metadata of BatchReportResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BatchReportResponse',
      type: {
        name: 'Composite',
        className: 'BatchReportResponse',
        modelProperties: {
          aggregateComputeTime: {
            required: false,
            serializedName: 'aggregateComputeTime',
            type: {
              name: 'Number'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'pending', 'finished' ]
            }
          },
          created: {
            required: false,
            serializedName: 'created',
            type: {
              name: 'DateTime'
            }
          },
          pending: {
            required: false,
            serializedName: 'pending',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'OperationInfoResponseElementType',
                  type: {
                    name: 'Composite',
                    className: 'OperationInfoResponse'
                  }
              }
            }
          },
          completed: {
            required: false,
            serializedName: 'completed',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'OperationInfoResponseElementType',
                  type: {
                    name: 'Composite',
                    className: 'OperationInfoResponse'
                  }
              }
            }
          },
          failed: {
            required: false,
            serializedName: 'failed',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'OperationInfoResponseElementType',
                  type: {
                    name: 'Composite',
                    className: 'OperationInfoResponse'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = BatchReportResponse;
