/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * A summary with a url for a status report on a specific batch id
 *
 */
class BatchLinkResponse {
  /**
   * Create a BatchLinkResponse.
   * @member {uuid} [batchId] the id of the batch
   * @member {date} [created] the time that the batch was submitted
   * @member {string} [url] a url for a status report on the batch
   */
  constructor() {
  }

  /**
   * Defines the metadata of BatchLinkResponse
   *
   * @returns {object} metadata of BatchLinkResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BatchLinkResponse',
      type: {
        name: 'Composite',
        className: 'BatchLinkResponse',
        modelProperties: {
          batchId: {
            required: false,
            serializedName: 'batchId',
            type: {
              name: 'String'
            }
          },
          created: {
            required: false,
            serializedName: 'created',
            type: {
              name: 'DateTime'
            }
          },
          url: {
            required: false,
            serializedName: 'url',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = BatchLinkResponse;
