/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Report indicating if a batch has been successfully submitted, providing an
 * endpoint to monitor batch progress
 *
 */
class BatchStartReportResponse {
  /**
   * Create a BatchStartReportResponse.
   * @member {boolean} [success] indicates that that batch was successfully
   * submitted
   * @member {string} [error] if the batch was not submitted successfully,
   * there will be an error message
   * @member {uuid} [id] the id of the batch
   * @member {string} [statusEndpoint] if the batch was submitted successfully,
   * the url of an endpoint for checking batch progress
   * @member {array} [operationIds] if the batch was submitted successfully, a
   * list of the ids of submitted operations,
   * in the same order as the submitted operations
   */
  constructor() {
  }

  /**
   * Defines the metadata of BatchStartReportResponse
   *
   * @returns {object} metadata of BatchStartReportResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BatchStartReportResponse',
      type: {
        name: 'Composite',
        className: 'BatchStartReportResponse',
        modelProperties: {
          success: {
            required: false,
            serializedName: 'success',
            type: {
              name: 'Boolean'
            }
          },
          error: {
            required: false,
            serializedName: 'error',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          statusEndpoint: {
            required: false,
            serializedName: 'statusEndpoint',
            type: {
              name: 'String'
            }
          },
          operationIds: {
            required: false,
            serializedName: 'operationIds',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'UuidElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = BatchStartReportResponse;
