/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Container for submitting batches of transform graphs
 *
 */
class Batch {
  /**
   * Create a Batch.
   * @member {array} items Collection of transform graphs for processing. Each
   * item represents a single billable operation.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Batch
   *
   * @returns {object} metadata of Batch
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Batch',
      type: {
        name: 'Composite',
        className: 'Batch',
        modelProperties: {
          items: {
            required: true,
            serializedName: 'items',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TransformGraphElementType',
                  type: {
                    name: 'Composite',
                    className: 'TransformGraph'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Batch;
