/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Object used to represent border thickness.
 *
 */
class Bounds {
  /**
   * Create a Bounds.
   * @member {number} top Width of top border.
   * @member {number} left Width of left border.
   * @member {number} bottom Width of bottom border.
   * @member {number} right Width of right border
   */
  constructor() {
  }

  /**
   * Defines the metadata of Bounds
   *
   * @returns {object} metadata of Bounds
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Bounds',
      type: {
        name: 'Composite',
        className: 'Bounds',
        modelProperties: {
          top: {
            required: true,
            serializedName: 'top',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          },
          left: {
            required: true,
            serializedName: 'left',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          },
          bottom: {
            required: true,
            serializedName: 'bottom',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          },
          right: {
            required: true,
            serializedName: 'right',
            constraints: {
              InclusiveMaximum: 1000,
              InclusiveMinimum: 0
            },
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Bounds;
