/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Creates a border of specified width and color around the source.
 *
 * @extends models['TransformUnit']
 */
class ImageExtend extends models['TransformUnit'] {
  /**
   * Create a ImageExtend.
   * @member {object} extend The width of the border
   * @member {number} [extend.top] Width of top border.
   * @member {number} [extend.left] Width of left border.
   * @member {number} [extend.bottom] Width of bottom border.
   * @member {number} [extend.right] Width of right border
   * @member {object} background The color of the border
   * @member {number} [background.r] The red component.
   * @member {number} [background.g] The green component.
   * @member {number} [background.b] The blue component.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageExtend
   *
   * @returns {object} metadata of ImageExtend
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_Extend',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageExtend',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          extend: {
            required: true,
            serializedName: 'extend',
            type: {
              name: 'Composite',
              className: 'Bounds'
            }
          },
          background: {
            required: true,
            serializedName: 'background',
            type: {
              name: 'Composite',
              className: 'Color'
            }
          }
        }
      }
    };
  }
}

module.exports = ImageExtend;
