/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Resize image with touch-from-inside semantics where width and height
 * represent maximums. e.g. the image will be
 * no larger that the bounding-box.
 * Aspect ratio is preserved, so image will be smaller than or equal to the
 * bounding box in one dimension, and
 * exactly fit the other dimension
 *
 * @extends models['TransformUnit']
 */
class ImageResizeMax extends models['TransformUnit'] {
  /**
   * Create a ImageResizeMax.
   * @member {number} width Maximum width
   * @member {number} height Maximum height
   * @member {string} [resizeKernel] The resampling algorithm used for
   * resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
   * 'nearest'. Default value: 'lanczos3' .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageResizeMax
   *
   * @returns {object} metadata of ImageResizeMax
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_ResizeMax',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageResizeMax',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          width: {
            required: true,
            serializedName: 'width',
            type: {
              name: 'Number'
            }
          },
          height: {
            required: true,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          resizeKernel: {
            required: false,
            serializedName: 'resizeKernel',
            defaultValue: 'lanczos3',
            type: {
              name: 'Enum',
              allowedValues: [ 'lanczos3', 'lanczos2', 'cubic', 'nearest' ]
            }
          }
        }
      }
    };
  }
}

module.exports = ImageResizeMax;
