/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Output to Jpeg
 *
 * @extends models['TransformUnit']
 */
class ImageFormatJpeg extends models['TransformUnit'] {
  /**
   * Create a ImageFormatJpeg.
   * @member {number} [quality] Jpeg quality. Default value: 80 .
   * @member {boolean} [progressive] Create progressive/interlace scan jpeg.
   * Default value: false .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageFormatJpeg
   *
   * @returns {object} metadata of ImageFormatJpeg
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ImageFormat_Jpeg',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageFormatJpeg',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          quality: {
            required: false,
            serializedName: 'quality',
            defaultValue: 80,
            constraints: {
              InclusiveMaximum: 100,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          progressive: {
            required: false,
            serializedName: 'progressive',
            defaultValue: false,
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = ImageFormatJpeg;
