/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Change image colors to tinted monochrome
 *
 * @extends models['TransformUnit']
 */
class ImageTint extends models['TransformUnit'] {
  /**
   * Create a ImageTint.
   * @member {object} tint The tint color
   * @member {number} [tint.r] The red component.
   * @member {number} [tint.g] The green component.
   * @member {number} [tint.b] The blue component.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageTint
   *
   * @returns {object} metadata of ImageTint
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_Tint',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageTint',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          tint: {
            required: true,
            serializedName: 'tint',
            type: {
              name: 'Composite',
              className: 'Color'
            }
          }
        }
      }
    };
  }
}

module.exports = ImageTint;
