/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Resize image with touch-from-outside semantics with manual positioning of
 * crop area via the gravity parameter.
 *
 * @extends models['TransformUnit']
 */
class ImageResizeCrop extends models['TransformUnit'] {
  /**
   * Create a ImageResizeCrop.
   * @member {number} width Output width
   * @member {number} height Output height
   * @member {string} [gravity] Position of crop area by gravity. Possible
   * values include: 'center', 'centre', 'north', 'northeast', 'east',
   * 'southeast', 'south', 'southwest', 'west', 'northwest'. Default value:
   * 'center' .
   * @member {string} [resizeKernel] The resampling algorithm used for
   * resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
   * 'nearest'. Default value: 'lanczos3' .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageResizeCrop
   *
   * @returns {object} metadata of ImageResizeCrop
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_ResizeCrop',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageResizeCrop',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          width: {
            required: true,
            serializedName: 'width',
            type: {
              name: 'Number'
            }
          },
          height: {
            required: true,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          gravity: {
            required: false,
            serializedName: 'gravity',
            defaultValue: 'center',
            type: {
              name: 'Enum',
              allowedValues: [ 'center', 'centre', 'north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest' ]
            }
          },
          resizeKernel: {
            required: false,
            serializedName: 'resizeKernel',
            defaultValue: 'lanczos3',
            type: {
              name: 'Enum',
              allowedValues: [ 'lanczos3', 'lanczos2', 'cubic', 'nearest' ]
            }
          }
        }
      }
    };
  }
}

module.exports = ImageResizeCrop;
