/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Resize the image to a specific height. Width will depend on aspect ratio of
 * image.
 *
 * @extends models['TransformUnit']
 */
class ImageResizeToHeight extends models['TransformUnit'] {
  /**
   * Create a ImageResizeToHeight.
   * @member {number} height Output height
   * @member {string} [resizeKernel] The resampling algorithm used for
   * resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
   * 'nearest'. Default value: 'lanczos3' .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageResizeToHeight
   *
   * @returns {object} metadata of ImageResizeToHeight
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_ResizeToHeight',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageResizeToHeight',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          height: {
            required: true,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          resizeKernel: {
            required: false,
            serializedName: 'resizeKernel',
            defaultValue: 'lanczos3',
            type: {
              name: 'Enum',
              allowedValues: [ 'lanczos3', 'lanczos2', 'cubic', 'nearest' ]
            }
          }
        }
      }
    };
  }
}

module.exports = ImageResizeToHeight;
