/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Resize image with touch-from-outside semantics with automatic positioning of
 * crop area using two different
 * strategies
 *
 * @extends models['TransformUnit']
 */
class ImageResizeAutoCrop extends models['TransformUnit'] {
  /**
   * Create a ImageResizeAutoCrop.
   * @member {number} width Output width
   * @member {number} height Output height
   * @member {string} [strategy] Strategy used for positioning crop area.
   * Possible values include: 'attention', 'entropy'. Default value:
   * 'attention' .
   * @member {string} [resizeKernel] The resampling algorithm used for
   * resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
   * 'nearest'. Default value: 'lanczos3' .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageResizeAutoCrop
   *
   * @returns {object} metadata of ImageResizeAutoCrop
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image_ResizeAutoCrop',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageResizeAutoCrop',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          width: {
            required: true,
            serializedName: 'width',
            type: {
              name: 'Number'
            }
          },
          height: {
            required: true,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          strategy: {
            required: false,
            serializedName: 'strategy',
            defaultValue: 'attention',
            type: {
              name: 'Enum',
              allowedValues: [ 'attention', 'entropy' ]
            }
          },
          resizeKernel: {
            required: false,
            serializedName: 'resizeKernel',
            defaultValue: 'lanczos3',
            type: {
              name: 'Enum',
              allowedValues: [ 'lanczos3', 'lanczos2', 'cubic', 'nearest' ]
            }
          }
        }
      }
    };
  }
}

module.exports = ImageResizeAutoCrop;
