/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Output to Webp
 *
 * @extends models['TransformUnit']
 */
class ImageFormatWebp extends models['TransformUnit'] {
  /**
   * Create a ImageFormatWebp.
   * @member {number} [quality] Webp compression level. Default value: 80 .
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ImageFormatWebp
   *
   * @returns {object} metadata of ImageFormatWebp
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ImageFormat_Webp',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'ImageFormatWebp',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          quality: {
            required: false,
            serializedName: 'quality',
            defaultValue: 80,
            constraints: {
              InclusiveMaximum: 100,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = ImageFormatWebp;
