/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.TransformUnit = require('./transformUnit');
exports.TransformGraph = require('./transformGraph');
exports.Batch = require('./batch');
exports.BatchStartReportResponse = require('./batchStartReportResponse');
exports.BatchLinkResponse = require('./batchLinkResponse');
exports.AllBatchesPageResponse = require('./allBatchesPageResponse');
exports.OperationInfoResponse = require('./operationInfoResponse');
exports.BatchReportResponse = require('./batchReportResponse');
exports.OperationStatusReportResponse = require('./operationStatusReportResponse');
exports.TransformGraphMetadataEnvelope = require('./transformGraphMetadataEnvelope');
exports.StorageSourceS3 = require('./storageSourceS3');
exports.StorageSinkS3 = require('./storageSinkS3');
exports.ImageGrayscale = require('./imageGrayscale');
exports.Bounds = require('./bounds');
exports.Color = require('./color');
exports.ImageExtend = require('./imageExtend');
exports.ImageResizeAutoCrop = require('./imageResizeAutoCrop');
exports.ImageResizeCrop = require('./imageResizeCrop');
exports.ImageResizeMax = require('./imageResizeMax');
exports.ImageResizeMin = require('./imageResizeMin');
exports.ImageResizeToHeight = require('./imageResizeToHeight');
exports.ImageResizeToWidth = require('./imageResizeToWidth');
exports.ImageTint = require('./imageTint');
exports.ImageFormatJpeg = require('./imageFormatJpeg');
exports.ImageFormatPng = require('./imageFormatPng');
exports.ImageFormatTiff = require('./imageFormatTiff');
exports.ImageFormatWebp = require('./imageFormatWebp');
exports.UnitUnknown = require('./unitUnknown');
exports.discriminators = {
  'TransformUnit' : exports.TransformUnit,
  'TransformUnit.StorageSource_S3' : exports.StorageSourceS3,
  'TransformUnit.StorageSink_S3' : exports.StorageSinkS3,
  'TransformUnit.Image_Grayscale' : exports.ImageGrayscale,
  'TransformUnit.Image_Extend' : exports.ImageExtend,
  'TransformUnit.Image_ResizeAutoCrop' : exports.ImageResizeAutoCrop,
  'TransformUnit.Image_ResizeCrop' : exports.ImageResizeCrop,
  'TransformUnit.Image_ResizeMax' : exports.ImageResizeMax,
  'TransformUnit.Image_ResizeMin' : exports.ImageResizeMin,
  'TransformUnit.Image_ResizeToHeight' : exports.ImageResizeToHeight,
  'TransformUnit.Image_ResizeToWidth' : exports.ImageResizeToWidth,
  'TransformUnit.Image_Tint' : exports.ImageTint,
  'TransformUnit.ImageFormat_Jpeg' : exports.ImageFormatJpeg,
  'TransformUnit.ImageFormat_Png' : exports.ImageFormatPng,
  'TransformUnit.ImageFormat_Tiff' : exports.ImageFormatTiff,
  'TransformUnit.ImageFormat_Webp' : exports.ImageFormatWebp,
  'TransformUnit.Unit_Unknown' : exports.UnitUnknown
};
