/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * A report of the id and an endpoint for checking the status of an operation
 *
 */
class OperationInfoResponse {
  /**
   * Create a OperationInfoResponse.
   * @member {uuid} [id] the id of the operation
   * @member {string} [url] an endpoint for a summary of the operation
   */
  constructor() {
  }

  /**
   * Defines the metadata of OperationInfoResponse
   *
   * @returns {object} metadata of OperationInfoResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'OperationInfoResponse',
      type: {
        name: 'Composite',
        className: 'OperationInfoResponse',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          url: {
            required: false,
            serializedName: 'url',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = OperationInfoResponse;
