/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * a processing summary of an operation
 *
 */
class OperationStatusReportResponse {
  /**
   * Create a OperationStatusReportResponse.
   * @member {date} [created] when the operation was created
   * @member {string} [status] the current status of the operation. Possible
   * values include: 'pending', 'failed', 'success'
   * @member {string} [error] if the operation has a status of "failed", this
   * will contain an error message
   * @member {number} [elapsedMicroseconds] time taken for an operation
   * @member {string} [operationDescriptionUrl] an endpoint that provides the
   * original operation parameters
   */
  constructor() {
  }

  /**
   * Defines the metadata of OperationStatusReportResponse
   *
   * @returns {object} metadata of OperationStatusReportResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'OperationStatusReportResponse',
      type: {
        name: 'Composite',
        className: 'OperationStatusReportResponse',
        modelProperties: {
          created: {
            required: false,
            serializedName: 'created',
            type: {
              name: 'DateTime'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'pending', 'failed', 'success' ]
            }
          },
          error: {
            required: false,
            serializedName: 'error',
            type: {
              name: 'String'
            }
          },
          elapsedMicroseconds: {
            required: false,
            serializedName: 'elapsedMicroseconds',
            type: {
              name: 'Number'
            }
          },
          operationDescriptionUrl: {
            required: false,
            serializedName: 'operationDescriptionUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = OperationStatusReportResponse;
