/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Target type for TransformUnits that are unrecognized at the current schema
 * level
 *
 * @extends models['TransformUnit']
 */
class UnitUnknown extends models['TransformUnit'] {
  /**
   * Create a UnitUnknown.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of UnitUnknown
   *
   * @returns {object} metadata of UnitUnknown
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Unit_Unknown',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'TransformUnit',
        className: 'UnitUnknown',
        modelProperties: {
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = UnitUnknown;
